### ISSUE TITLE
Federating MutatingWebhookConfiguration Type

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/federation-v2#389]
The Istio sidecar-injector pod patches the client `caBundle` of the `MutatingWebhookConfiguration` resource with the sidecar-injector secret data, and therefore can not be federated. When the resource gets patched, the `resourceVersion` field is updated, causing a propagated version mismatch between the federated and target resources. When the sync controller sees the mismatch, it will re-propagate the `MutatingWebhookConfiguration` resource which contains the empty `caBundle`. For the time being, deploy the `MutatingWebhookConfiguration` resource to clusters individually.

**Comment by marun** [comment]
The two comparison fields supported by for push propagation are `resourceVersion` (increments on all changes) and `generation` (increments on spec changes).  Neither would appear to allow for spec changes that federation should ignore.  

There is already [special handling](https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/controller/sync/controller.go#L731) of services to retain controller-supplied `clusterIP` and port configuration.  A possible fix would be enabling optional retention of an arbitrary field, maybe via overrides (optional since this requirement seems istio-specific)?

**Comment by danehans** [comment]
@marun thanks for the response. I'll test using `generation` during my next deployment and update this issue accordingly.

**Comment by danehans** [comment]
@marun Using `generation`, thanks for the pointer. I could not find a `kubefed2 federate` cmd flag that would allow me set `comparisonField`, so I patched the `FederatedTypeConfig` afterward.

**Comment by marun** [comment]
@danehans What about `--comparison-field`?  It's a flag to `enable`.

**Comment by danehans** [comment]
I see it now. Thanks! I will consider this issue closed.
