### ISSUE TITLE
Option to specify propagate resource to all cluster

### ISSUE THREAD

**Issue by shashidharatd** [kubernetes-sigs/federation-v2#401]
Currently, the placement objects are designed such that if you wish to propagate the federated resource to a member cluster, then one need to explicitly specify the cluster name in corresponding placement object. This could be hard as the cluster members could added/removed over time and user needs to keep updating the placement objects of federated resource. There is a clear desire to be able to specify the intent that the federated resource should be propagated to member clusters without additional steps.

Background:
For `cross-cluster service discovery` feature, there is a need to update federation map in Cluster DNS. We could achieve this by creating a `FederatedConfigMap` in federation and specifying a placement object which would take care of propagating the configmap to all members clusters. it should also take care of propagating to any newly joined cluster.
Note: Currently, if the cluster name is not present in the placement object the resource is removed during propagation, which could have some impact on the service discovery within the cluster.

To facilitate such a behaviour, i do not have a clear solution, but have some thoughts.
1. Introduce some special keyword (like `*` or `all`) which when specified as `clusterNames` the resource will be propagated to all member clusters.
2. Introduce a new field in placement (like `propogateToAllClusters`) which when set to true, the controller will take care of federating to all member clusters.

/cc @irfanurrehman @marun @kubernetes-sigs/federation-wg 

p.s: This is partly brought out in https://github.com/kubernetes-sigs/federation-v2/issues/87, but i created a separate issue to disambiguate between the little different but related requirement.

**Comment by tghartland** [comment]
I have been writing down some rough ideas for what advanced placement might look like, that I started writing after looking at #87.

I do not know what the implementation process would be like for something like this, so it is may be that some of the things could be impossible. I also don't know if something like this fits in with the current design goals for federation-v2.

If you have the time, please take a look and give some feedback if you can.  
https://gist.github.com/tghartland/a09b351eec5168720b76df12f8538bb0

**Comment by shashidharatd** [comment]
> @shashidharatd not sure if this is still the case but historically an empty label selector meant all. Is there a specific reason while we cannot use the same approach?
I'm not 100% sure that adding a special keyword would be consistent with the traditional kube APIs.

AFAIK, there is no `label selector` based placement implementation of any sort in federation-v2. @font, can you please confirm.

**Comment by marun** [comment]
I can confirm that there is currently no selector-based placement available in fedv2.  I've had reservations about using selectors to provide associativity between primitives, but I think it makes sense to use selectors for placement.  Either selector-based placement could be added to the current scheme, or the existing name-based strategy removed in favor of selectors.  We're still in alpha, so deprecation or compatibility is not strictly required.

I would prefer implementation to wait until I have completed the in-progress transition to generated primitives.  I don't think it makes sense to maintain code that will be removed in the near term (< 2 weeks).

@tghartland If selector-based placement became the default, would the proposal you linked to in your gist still be necessary?  I'm not sure I understand the need for hierarchical labeling, and I wonder if better labeling wouldn't address most of the concerns you propose to address.

**Comment by tghartland** [comment]
@marun my main concern was that I had over complicated things.

I thought about a hierarchy because in the suggestion in #87 it has `region=eu, zone=east`, and I felt that `zone=east` on its own is an odd thing to have, because I think nobody would ever want to select us-east, eu-east and asia-east all at once. `zone` would only ever be used to limit within a region. 

I think this is an important point as well
> I suppose that is what the inclusivity should be used for. It's the difference between interpreting an absent selector as "I don't want any of these clusters" and "I don't care about this selector".

In my example, placement on a cluster with GPU resources should be opt-in only, so that only workloads which require GPUs are placed on those clusters. With simple label based selection, you would at least have to have some way to say that if no GPU label is specified then it should default to `gpu: none`. And you would also then be required to label each cluster without GPUs with that label. Right?

**Comment by marun** [comment]
@tghartland It may be that nobody would ever use `zone=east` on its own.  That doesn't preclude implicit hierarchy - i.e. `region=eu` includes all zones in that region - and I'm not sure what the value would be in imposing explicit hierarchy.

Regarding your gist's questions about troubleshooting selectors, I can see the value in adding something to `kubefed2` that would allow testing of a selector statement against the current set of `FederatedCluster` instances.  

I think advanced placement (i.e. a controller that manages placement resources) is suggested for the example in your most recent comment.  Maybe even OPA integration (as per fedv1), since it sounds like it is an application of policy to placement more than placement itself.

**Comment by tghartland** [comment]
@marun in any case I would be happy to see label based selection over the current naming method. Any higher level management can come after that, if needed.

**Comment by marun** [comment]
I'm working on replacing name-based placement with a selector-based scheme.
