### ISSUE TITLE
Enable LeaderElect for federation controller 

### ISSUE THREAD

**Issue by fisherxu** [kubernetes-sigs/federation-v2#402]
Now the federation-controller is deployed through statefulset and without LeaderElect only can in single instance. But in the following scenarios, we need to deploy the federation-controller in multiple instances for high availability with LeaderElect:

1. Need to deploy multiple instances in several nodes, in case of node crash then the slave controller can acquire leadership and serve soon.
2. If the leader controller lost connection to the kube-apiserver but still running, the healthy slave controller can acquire leadership and serve soon.

And if using multiple instances with LeaderElect, I think deploy the controller through deployment is fine.
BTW, the LeaderElect code is taken from kubernetes, and haven't made any changes yet :)

PTAL and request for your comments
/cc @font @irfanurrehman @marun @pmorie @shashidharatd

**Comment by marun** [comment]
I'm not sure why leader election is worth pursuing in advance of users validating the general direction of federation.   The complexity is real, the benefits are not (at least not yet).  I'm also concerned that the challenges of high availability federation are likely to be related to the involvement of multiple clusters, and that leader election as proposed is really only intended to achieve HA within a single cluster.

Even a federation control plane that stays up in the host cluster due to a mechanism like leader election can be a single point of failure when connectivity between the host cluster and one or more member clusters is interrupted for whatever reason.  The best guess at ensuring federation control plane reliability is 'pull reconciliation', in which the federation control plane writes configuration to a distributed backing store shared with the member clusters, and those clusters use local agents to apply the configuration.

So my cone

**Comment by fisherxu** [comment]
> that leader election as proposed is really only intended to achieve HA within a single cluster.

and yes, this is target to the HA within a single cluster, and it's just a base framwork, user can also set it to false so disable it and benefits is to users.

And to the member clusters health checking, that's should be another feature. They are all necessary and important.

**Comment by marun** [comment]
@fisherxu I hear that adding leader election is desirable for your use case, and thank you for putting up with my uncertaintly.  I think there need to be 2 paths:
 
  - a statefulsets-based option that doesn't enable leader election
  - a deployment-based option that does enable leader election

The helm installer would ideally allow the user to select either option.  I'm not sure the deployment script should be deploying leader election, but unless @gyliu513 is making progress adding ci validation of the helm chart there may be no choice.

**Comment by fisherxu** [comment]
@marun Thanks for reminder, and there is a enableLeaderElection option in the PR, so users can disable it.

**Comment by marun** [comment]
@fisherxu I understand that it can be disabled.  My comment was meant to indicate that there needs to be an implementation path for deployments + leader election and stateful sets without leader election.  If you don't intend to implement those paths that could be ok but there should be issues that point other people in the right direction to complete the work.

**Comment by shashidharatd** [comment]
Now the leader election is added to controller-manager in PR #632, following this are pending.
- [ ] Document enabling leader-election for controller-manager.
- [ ] Select the appropriate deployment method for running controller-manager with leader election

**Comment by marun** [comment]
@shashidharatd Are you still working on adding documentation for leader election to the userguide?  It doesn't have to be exhaustive, but at least a short indication of what leader election is, why federation enables it by default, and how it can be configured.
