### ISSUE TITLE
kubefed2: some suggestion about kubefed2 command

### ISSUE THREAD

**Issue by magicwang-cn** [kubernetes-sigs/federation-v2#513]
currently, kubefed2 is a total tool to manage federation controller plane. we should focus on its use experience to make it more reliable :).

**some suggestions:**
- `join`: maybe we should check the cluster's environment first to avoid do the wrong work. currently, once join the cluster failed(create sa failed, create secret failed, or create clusterrole failed, etc.), we can't do the join work second time(because there are left resources that have been created before). so the check process is necessary, we can check the cluster if it is suitable to be joined
- `unjoin`: we should ignore the specific `404` error when deleting the federation related resources

**questions:**
- does one cluster can be joined to more than one federation controller plane?
- when the cluster is unjoined from federation controller plane, do we need to delete the clustered resources which is created by federated resources, for example, we create a federateddeployment with placement(`cluster1 and cluster2`), if we unjoin the cluster2, should we delete the deployment which is created by federation controller plane in the cluster2?

@marun @irfanurrehman

**Comment by magicwang-cn** [comment]
@gyliu513 this can't slove all the problems. `unjoin --force` just force to delete the federated cluster and secret in the federation controller plane, but some resources are still left in the `unjoined cluster`, next time, if we want join the cluster again, it will failed.

**Comment by gyliu513** [comment]
@magicwang-cn if with `unjoin --force`, there are still some garbage data, then there might be something wrong with your k8s cluster, if you check the `unjoin --force` logic, it is actually trying to delete all of the resource even if some steps failed.

FYI @xunpan for more comments.

**Comment by magicwang-cn** [comment]
@gyliu513 yes, i know `unjoin --force` will delete all of the resource(just in the federation controller plane/hostcluster) even if some steps failed, but the cluster which has been unjoined still left some resources, this will effect the `join` process(if we want to join the cluster again)

**Comment by xunpan** [comment]
@magicwang-cn ,
Currently, unjoin is an operation opposite to join. It only deleted resources created for federation cluster management itself.

In your case, I guess federated resources, like Deployment, is left in the unjoin cluster. The related resource is generated by federation resource. You're trying to use unjoin to clean related resources. However, it does not work currently.

I think clean related resource in the unjoin cluster is a meaningful operation. However, it may be expensive if lots of resources are there. What do you think @gyliu513 @marun

**Comment by gyliu513** [comment]
@magicwang-cn @xunpan please refer to https://github.com/kubernetes-sigs/federation-v2/issues/510 and https://github.com/kubernetes-sigs/federation-v2/pull/518 for some detail, we already mentioned to end user that the federated resources should be deleted before unjoin cluster.

**Comment by marun** [comment]
If a user wants to remove federated resources from one or more member clusters, placement policy is the only way to reliably accomplish that goal.  It should not be the responsibility of `kubefed2` since it would involve considerable coordination with the scheduling and sync controllers that run in the federation control plane.

**Comment by marun** [comment]
@magicwang-cn I can see the utility in adding a `--force` option to `kubefed2 join` that will remove existing resources  in the cluster targeted for join (rather than failing as it does today).    Is that  what you're suggesting?

To you questions:

 - A member cluster can belong to only a single cluster-scoped federation.  A member cluster can belong to as many namespace-scoped federations as it has namespaces.
 - I don't think `kubefed2` should be responsible for removing federated resources from member clusters.  Doing so would involve considerable coordination with the sync and scheduling controllers which reside in the control plane.  Placement policy is the way to remove federated resources from member clusters, and if/when user requirements dictate we can explore ways of applying policy before unjoining a cluster (e.g. remove cluster from `clusterNames` of all resources or have a way of influencing similar behavior for selector- and scheduling-determined placement).

**Comment by magicwang-cn** [comment]
@marun yes. another way, maybe `check` before `join` is more friendly to the developers.

**Comment by magicwang-cn** [comment]
@marun what is the cluster-scoped federation, do you meaning the `--federation-namespace` with different values?("" for cluster-scoped and "xxx" for namespace-scoped).

**Comment by gyliu513** [comment]
@magicwang-cn please refer to https://github.com/kubernetes-sigs/federation-v2/blob/master/docs/userguide.md#namespaced-federation for what is namespaced federation.

**Comment by magicwang-cn** [comment]
@gyliu513 OK, tks. sorry, i did't see it before :(

**Comment by marun** [comment]
With the addition of idempotent join (#555) and unjoin (#431), I think this issue can be closed.  Feel free to reopen.
