### ISSUE TITLE
method to delete deployed resources on unjoin 

### ISSUE THREAD

**Issue by matti** [kubernetes-sigs/federation-v2#583]
**What would you like to be added**:
remove deployments on unjoin

**Why is this needed**:
currently when a cluster is unjoined, all deployments/pods remain running

/kind feature

**Comment by xunpan** [comment]
There has similar discussion in ticket #513

unjoin operation is just opposite operation to join. It is not designed for clean resources created by federated resources, e.g. federateddeployment in your case, in member clusters.

Comments https://github.com/kubernetes-sigs/federation-v2/issues/513#issuecomment-448016763 describes the detailed reason.

**Comment by matti** [comment]
understood - but how can I know in the unjoined cluster that it has unjoined?

**Comment by marun** [comment]
There is no definitive way for a member cluster to know whether it has been unjoined from a federation.  As per the linked comment, removal of federated resources from member clusters prior to unjoin would need to be effected by placement changes.

**Comment by matti** [comment]
I think it should be possible to:

create an operator in the member cluster that notices that it has been unjoined and then it will destroy all the resources.

reason: the unjoin may be issued by another admin who no-longer wishes to see the cluster in the federation - I think it's not right that the another admin goes in to the member cluster and deletes everything from it.

**Comment by marun** [comment]
An operator as you've described does not make sense to me.  Fedv2 with push propagation is not intended to be used in a scenario where close coordination between admins isn't the rule.  Anyone with admin privileges to the federation control plane has defacto control over configuration in member clusters, including right of deletion.  I don't understand the value in supporting the removal of that control in arbitrary ways, as it seems like a corner-case that is unlikely to justify the effort involved.

If control over application of configuration in a member cluster needs to be decentralized, I think a better solution would be 'pull propagation' (configuration generated from federation control plane into a persistent store that is used a source of truth by kube-applier running in member clusters).  This has been discussed but thus far remains unimplemented due to a lack of demand.

**Comment by matti** [comment]
okay, since what I want to do "does not make sense", I'm gonna close this in favour of a smaller subset in #585 so that I can do what I think that makes sense to me.
