### ISSUE TITLE
body was not decodable (unable to check for Status): Object 'Kind' is missing

### ISSUE THREAD

**Issue by cooktheryan** [kubernetes-sigs/federation-v2#705]
**What happened**: No issues in use but the logs of the federation controller manager repeatedly an error.

**What you expected to happen**: No errors

**How to reproduce it (as minimally and precisely as possible)**: Deploy a federated namespace cluster and then run kubectl logs -f federation-controller-manager-specific-pod

**Anything else we need to know?**: 
```
E0328 15:25:15.215813       1 reflector.go:134] github.com/kubernetes-sigs/federation-v2/pkg/controller/sync/accessor.go:164: Failed to list <nil>: the server could not find the requested resource
I0328 15:25:15.454506       1 leaderelection.go:245] successfully renewed lease pacman/federation-controller-manager
I0328 15:25:16.220615       1 reflector.go:169] Listing and watching <nil> from github.com/kubernetes-sigs/federation-v2/pkg/controller/sync/accessor.go:164
I0328 15:25:16.222713       1 request.go:1144] body was not decodable (unable to check for Status): Object 'Kind' is missing in '{
  "paths": [
    "/apis",
    "/metrics",
    "/swagger-ui/",
    "/version"
  ]
}'
E0328 15:25:16.222743       1 reflector.go:134] github.com/kubernetes-sigs/federation-v2/pkg/controller/sync/accessor.go:164: Failed to list <nil>: the server could not find the requested resource
```
## gist of deployment and federatedtypeconfig
https://gist.github.com/cooktheryan/83109f825cd4c62145c07c03e1d422a2

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.4
- Federation version quay.io/kubernetes-multicluster/federation-v2:v0.0.7
- Install method (helm vs script): Operator script
- Install configuration (namespaced vs cluster-scoped) namespace
- Others

/kind bug

**Comment by marun** [comment]
@cooktheryan The error here indicates the failure of the sync controller to launch an informer.  That can occur when a `FederatedTypeConfig` refers to an API type that does not exist.  Given that the only supported deployment method for this repo is via the helm chart, and I can't reproduce the problem deploying with a chart, I'm left with the assumption that the cause of the problem you're seeing is related to the operator script mode of deployment rather than a bug with federation.  I've relabeled the issue accordingly.

That said, I'm happy to try to help diagnose the problem.  Please post (e.g. via gist, not on the issue directly) the federated type configs and summary of installed federated type crds (e.g via `kubectl api-resources`) for the deployment when you have a chance.

**Comment by cooktheryan** [comment]
It seems like the issue has gone away on it's own
