### ISSUE TITLE
Fail to join a new cluster

### ISSUE THREAD

**Issue by XiangLi0619** [kubernetes-sigs/federation-v2#783]
I installed the federation control plane and joined the host cluster. Before adding another cluster, how can I edit config and add the new cluster information? As someone new to kubernetes I was somehow confused with the user guide, because when I followed it 
`./bin/kubefed2 join federated1 --cluster-context federated1 \
    --host-cluster-context xxxx --add-to-registry --v=2`
I got
`I0421 22:27:32.530216   22738 join.go:165] Args and flags: name federated1, host: xxxx, host-system-namespace: federation-system, registry-namespace:  kube-multicluster-public, kubeconfig: , cluster-context: federated1, secret- name: , limited-scope: false, dry-run: false
I0421 22:27:32.533013   22738 join.go:184] Failed to get joining cluster conf ig: context "federated1" does not exist
F0421 22:27:32.533031   22738 join.go:133] Error: context "federated1" does not exist
`
What should I do before joining a new cluster to the federation?

**Comment by marun** [comment]
The context name for the cluster you are joining needs to exist prior to joining.   As per the log message, the kubeconfig context being used for `--cluster-context` was `federated1` (not `cluster2` as indicated in the command line you provided).  Note that, if not provided, `--cluster-context` will default to the name of the cluster you are attempting to join.

I encourage you to follow the guide exactly rather than varying the names while you develop familiarity with federation.  Otherwise, if you run into problems, troubleshooting may be more challenging.

**Comment by XiangLi0619** [comment]
Thanks @marun . I found what I missed and made it. This issue can be closed.
